import {
  logo,
  userImg,
  userBck,
  stars,
  telegram,
  arrow,
  expertise,
  stock_1,
  stock_2,
  stock_3,
  secondExpertise,
  courseImg,
  courseImg2,
  courseImg3,
  courseUser,
  testimonialImg,
  invoiceImg,
} from "../assets";

export const navLinks = [
  {
    id: "home",
    title: "Home",
  },
  {
    id: "subscription",
    title: "Subscription",
  },
  {
    id: "expertise",
    title: "Expertise",
  },
  {
    id: "webinar",
    title: "Webinar",
  },
  {
    id: "wallet",
    title: "Wallet",
  },
];

export const expertise_type = [
  {
    id: 1,
    image: expertise,
    title: "Futures",
    followers: "4K + More",
    describe:
      "Our SEBI Registered experts with their expertise, help traders gain a deeper understanding of risk management, leverage, and market dynamics for profitability.",
    button: "Explore All",
    arrowIcon: arrow,
  },
  {
    id: 2,
    image: expertise,
    title: "Commodity",
    followers: "4K + More",
    describe:
      "Our SEBI Registered experts with their expertise, help traders gain a deeper understanding of risk management, leverage, and market dynamics for profitability.",
    button: "Explore All",
    arrowIcon: arrow,
  },
  {
    id: 3,
    image: expertise,
    image2: secondExpertise,
    title: "Equity",
    followers: "4K + More",
    describe:
      "Our SEBI Registered experts with their expertise, help traders gain a deeper understanding of risk management, leverage, and market dynamics for profitability.",
    button: "Explore All",
    arrowIcon: arrow,
  },
];

export const courses = [
  {
    imageUrl: courseImg,
    title: "Insights at your fingertips",
    instructor: "Rohit Aggi",
    followers: "3.1k",
    experience: "7+",
    duration: "3 hrs",
    session: "3",
    price: "₹1,999/-",
  },
  {
    imageUrl: courseImg,
    title: "Insights at your fingertips",
    instructor: "Rohit Aggi",
    followers: "2.5k",
    experience: "5+",
    duration: "2 hrs",
    session: "2",
    price: "₹1,499/-",
  },

  {
    imageUrl: courseImg,
    title: "Insights at your fingertips",
    instructor: "Rohit Aggi",
    followers: "2.5k",
    experience: "5+",
    duration: "2 hrs",
    session: "2",
    price: "₹1,499/-",
  },
  {
    imageUrl: courseImg,
    title: "Insights at your fingertips",
    instructor: "Rohit Aggi",
    followers: "2.5k",
    experience: "5+",
    duration: "2 hrs",
    session: "2",
    price: "₹1,499/-",
  },
  {
    imageUrl: courseImg,
    title: "Insights at your fingertips",
    instructor: "Rohit Aggi",
    followers: "2.5k",
    experience: "5+",
    duration: "2 hrs",
    session: "2",
    price: "₹1,499/-",
  },
  {
    imageUrl: courseImg,
    title: "Insights at your fingertips",
    instructor: "Rohit Aggi",
    followers: "3.1k",
    experience: "7+",
    duration: "3 hrs",
    session: "3",
    price: "₹1,999/-",
  },
];

export const testimonialsData = [
  {
    id: 1,
    text: "Since 2019, Gravity team has been an astounding market maker for Bitkub. They have proven themselves to be one of the most consistent, committed and driven market makers on our exchange. Gravity Team has contributed high-quality volume and has proven to be very reliable and trustworthy partner. We strongly advocate Gravity Team as they have been an indispensable part of our market-making team.",
    author: "Atthakrit Chimplapibul",
    image: testimonialImg,
    designation: "CEO, Company A",
  },
  {
    id: 2,
    text: "Since 2019, Gravity team has been an astounding market maker for Bitkub. Gravity Team has contributed high-quality volume and has proven to be very reliable and trustworthy partner. We strongly advocate Gravity Team as they have been an indispensable part of our market-making team.",
    author: "Jane Smith",
    image: testimonialImg,
    designation: "CTO, Company B",
  },
  {
    id: 3,
    text: "Becoming an affiliate partner was a great decision. The referral program is rewarding and easy to use.",
    author: "Bob Johnson",
    image: testimonialImg,
    designation: "COO, Company C",
  },
];

// export const hero_experience = [
//   {
//     id: "1",
//     icon: userBck,
//     userImg: userImg,
//     name:"Arun Kumar",
//     content:
//       "The best credit cards offer some tantalizing combinations of promotions and prizes",
//   },
//   {
//     id: "2",
//     icon: shield,
//     title: "100% Secured",
//     content:
//       "We take proactive steps make sure your information and transactions are secure.",
//   },
//   {
//     id: "3",
//     icon: send,
//     title: "Balance Transfer",
//     content:
//       "A balance transfer credit card can save you a lot of money in interest charges.",
//   },
// ];

export const expertise_data = [
  {
    id: "1",
    icon: userBck,
    userImg: userImg,
    name: "Arun Kumar",
    title: "Stock Market",
    ratingIcon: stars,
    rating: "4.4",
    experience: "Experience",
    totalExp: "7+",
    followers: "Followers",
    totalFollowers: "3.1k",
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: "Join Telegram",
    arrowIcon: arrow,
  },
  {
    id: "2",
    icon: userBck,
    userImg: userImg,
    name: "Arun Kumar",
    title: "Stock Market",
    ratingIcon: stars,
    rating: "4.4",
    experience: "Experience",
    totalExp: "7+",
    followers: "Followers",
    totalFollowers: "3.1k",
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: "Join Telegram",
    arrowIcon: arrow,
  },
  {
    id: "3",
    icon: userBck,
    userImg: userImg,
    name: "Arun Kumar",
    title: "Stock Market",
    ratingIcon: stars,
    rating: "4.4",
    experience: "Experience",
    totalExp: "7+",
    followers: "Followers",
    totalFollowers: "3.1k",
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: "Join Telegram",
    arrowIcon: arrow,
  },
  {
    id: "4",
    icon: userBck,
    userImg: userImg,
    name: "Arun Kumar",
    title: "Stock Market",
    ratingIcon: stars,
    rating: "4.4",
    experience: "Experience",
    totalExp: "7+",
    followers: "Followers",
    totalFollowers: "3.1k",
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: "Join Telegram",
    arrowIcon: arrow,
  },
  {
    id: "5",
    icon: userBck,
    userImg: userImg,
    name: "Arun Kumar",
    title: "Stock Market",
    ratingIcon: stars,
    rating: "4.4",
    experience: "Experience",
    totalExp: "7+",
    followers: "Followers",
    totalFollowers: "3.1k",
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: "Join Telegram",
    arrowIcon: arrow,
  },
  {
    id: "6",
    icon: userBck,
    userImg: userImg,
    name: "Arun Kumar",
    title: "Stock Market",
    ratingIcon: stars,
    rating: "4.4",
    experience: "Experience",
    totalExp: "7+",
    followers: "Followers",
    totalFollowers: "3.1k",
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: "Join Telegram",
    arrowIcon: arrow,
  },
];

export const stock_data = [
  {
    id: "1",
    content:
      "Our platform offers easy-to-use tools and customised services to traders, authorised by SEBI registered Research Analysts, making it simple to execute trades and manage the portfolio.",
    title: "For Traders",
    img: stock_1,
  },
  {
    id: "2",
    content:
      "Connect with traders actively seeking valuable information, ensuring your analysis reaches an interested audience that enhances your visibility and credibility.",
    title: "For RAs",
    img: stock_2,
  },
  {
    id: "3",
    content:
      "A one stop solution platform that provides a transparent access to comprehensive analysis and a vibrant network of traders and experts and resources needed for informed decision-making and profitable trading journeys.",
    name: "Kenn Gallagher",
    title: "",
    img: stock_3,
  },
];

export const courseExpertise_data = [
  {
    id: "1",
    cardImg: courseImg,
    title: "Insights at your fingertips 1",
    image: courseUser,
    userName: "Rohit Aggi",
    ratingIcon: stars,
    rating: "4.4",
    telegramImg: telegram,
    experience: "Experience",
    totalExp: "7+",
    followers: "Followers",
    totalFollowers: "3.1k",
    callTime: "Duration : 3 hrs",
    callSession: "Session : 3",
    price: "₹1,999",
    btn: "Buy Now",
  },
  {
    id: "2",
    cardImg: courseImg,
    title: "Insights at your fingertips 2",
    image: courseUser,
    userName: "Rohit Aggi",
    ratingIcon: stars,
    rating: "4.4",
    telegramImg: telegram,
    experience: "Experience",
    totalExp: "7+",
    followers: "Followers",
    totalFollowers: "3.1k",
    callTime: "Duration : 3 hrs",
    callSession: "Session : 3",
    price: "₹1,999",
    btn: "Buy Now",
  },
  {
    id: "3",
    cardImg: courseImg,
    title: "Insights at your fingertips 3",
    image: courseUser,
    userName: "Rohit Aggi",
    ratingIcon: stars,
    rating: "4.4",
    telegramImg: telegram,
    experience: "Experience",
    totalExp: "7+",
    followers: "Followers",
    totalFollowers: "3.1k",
    callTime: "Duration : 3 hrs",
    callSession: "Session : 3",
    price: "₹1,999",
    btn: "Buy Now",
  },
  {
    id: "4",
    cardImg: courseImg2,
    title: "Insights at your fingertips 4",
    image: courseUser,
    userName: "Rohit Aggi",
    ratingIcon: stars,
    rating: "4.4",
    telegramImg: telegram,
    experience: "Experience",
    totalExp: "7+",
    followers: "Followers",
    totalFollowers: "3.1k",
    callTime: "Duration : 3 hrs",
    callSession: "Session : 3",
    price: "₹1,999",
    btn: "Buy Now",
  },
  {
    id: "5",
    cardImg: courseImg3,
    title: "Insights at your fingertips 5",
    image: courseUser,
    userName: "Rohit Aggi",
    ratingIcon: stars,
    rating: "4.4",
    telegramImg: telegram,
    experience: "Experience",
    totalExp: "7+",
    followers: "Followers",
    totalFollowers: "3.1k",
    callTime: "Duration : 3 hrs",
    callSession: "Session : 3",
    price: "₹1,999",
    btn: "Buy Now",
  },
];

export const expertsData = [
  {
    id: 1,
    image: userImg,
    name: "John Doe",
    role: "Stock Market",
    rating: 4.5,
    experience: "10+",
    followers: 5289,
    description:
      "Have full control of your business finances on the go using our iOS",
    prize: "5000",
  },

  {
    id: 2,
    image: userImg,
    name: "John Doe",
    role: "Stock Market",
    rating: 4.5,
    experience: "10+",
    followers: 5289,
    description:
      "Have full control of your business finances on the go using our iOS",
    prize: "5000",
  },

  {
    id: 3,
    image: userImg,
    name: "John Doe",
    role: "Stock Market",
    rating: 4.5,
    experience: "10+",
    followers: 5289,
    description:
      "Have full control of your business finances on the go using our iOS",
    prize: "5000",
  },

  {
    id: 4,
    image: userImg,
    name: "John Doe",
    role: "Stock Market",
    rating: 4.5,
    experience: "10+",
    followers: 5289,
    description:
      "Have full control of your business finances on the go using our iOS",
    prize: "5000",
  },

  {
    id: 5,
    image: userImg,
    name: "John Doe",
    role: "Stock Market",
    rating: 4.5,
    experience: "10+",
    followers: 5289,
    description:
      "Have full control of your business finances on the go using our iOS",
    prize: "5000",
  },

  {
    id: 6,
    image: userImg,
    name: "John Doe",
    role: "Stock Market",
    rating: 4.5,
    experience: "10+",
    followers: 5289,
    description:
      "Have full control of your business finances on the go using our iOS",
    prize: "5000",
  },
];

export const continueCoursesData = [
  {
    imageUrl: courseImg,
    title: "Continue Course 1",
    image: userImg,
    instructor: "Instructor 1",
    followers: 1500,
    experience: "2",
    duration: "2",
    session: "10",
    completedSession: "5",
  },
  {
    imageUrl: courseImg,
    title: "Continue Course 2",
    image: userImg,
    instructor: "Instructor 2",
    followers: 2000,
    experience: "3",
    duration: "3",
    session: "12",
    completedSession: "7",
  },
  {
    imageUrl: courseImg,
    title: "Continue Course 3",
    image: userImg,
    instructor: "Instructor 3",
    followers: 1800,
    experience: "2.5",
    duration: "2.5",
    session: "8",
    completedSession: "4",
  },
];

export const completedCoursesData = [
  {
    title: "Completed Course 1",
    imageUrl: courseImg,
    image: userImg,
    instructor: "Instructor 1",
    experience: "2 yrs",
    followers: "1000+",
    duration: "4 weeks",
    session: "20",
    completedSession: "20",
  },
  {
    title: "Completed Course 2",
    imageUrl: courseImg,
    image: userImg,
    instructor: "Instructor 2",
    experience: "3 yrs",
    followers: "1500+",
    duration: "6 weeks",
    session: "30",
    completedSession: "30",
  },
  {
    title: "Completed Course 2",
    imageUrl: courseImg,
    image: userImg,
    instructor: "Instructor 2",
    experience: "3 yrs",
    followers: "1500+",
    duration: "6 weeks",
    session: "30",
    completedSession: "30",
  },
];

export const recommendCoursesData = [
  {
    imageUrl: courseImg,
    rating: "4.4",
    title: "Continue Course 1",
    image: userImg,
    instructor: "Instructor 1",
    followers: 1500,
    experience: "2",
    duration: "2",
    session: "10",
    completedSession: "5",
  },
  {
    imageUrl: courseImg,
    title: "Continue Course 2",
    rating: "4.4",
    image: userImg,
    instructor: "Instructor 2",
    followers: 2000,
    experience: "3",
    duration: "3",
    session: "12",
    completedSession: "7",
  },
  {
    imageUrl: courseImg,
    title: "Continue Course 3",
    rating: "4.4",
    image: userImg,
    instructor: "Instructor 3",
    followers: 1800,
    experience: "2.5",
    duration: "2.5",
    session: "8",
    completedSession: "4",
  },
  {
    imageUrl: courseImg,
    title: "Continue Course 3",
    rating: "4.4",
    image: userImg,
    instructor: "Instructor 3",
    followers: 1800,
    experience: "2.5",
    duration: "2.5",
    session: "8",
    completedSession: "4",
  },
  {
    imageUrl: courseImg,
    title: "Continue Course 3",
    rating: "4.4",
    image: userImg,
    instructor: "Instructor 3",
    followers: 1800,
    experience: "2.5",
    duration: "2.5",
    session: "8",
    completedSession: "4",
  },
  {
    imageUrl: courseImg,
    title: "Continue Course 3",
    rating: "4.4",
    image: userImg,
    instructor: "Instructor 3",
    followers: 1800,
    experience: "2.5",
    duration: "2.5",
    session: "8",
    completedSession: "4",
  },
];

export const expertData = [
  {
    name: "Arun Kumar",
    role: "Futures & Options",
    experience: "7years",
    followers: "31.5k",
    description:
      "Take your team up a level with easy-to-use tools, effortless templates and efficient workflows.",
    rating: 4.4,
    image: userImg,
  },
];

export const sessionsData = Array.from({ length: 5 }, (_, index) => ({
  id: index + 1,
  title: `Session ${index + 1} Title`,
  description: "Get full control of your business finances.",
  duration: "20min",
}));

export const singleCourse = {
  imageUrl: courseImg,
  title: "Course Title",
  level: "Medium",
  duration: "7 hr 20m",
  sessions: 5,
  completedSessions: 3,
  amount: "₹ 1,999/-",
  buyDate: "28/01/2024",
  access: "Lifetime Access",
  sessionsDetails: sessionsData,
  aboutCourse:
    "Lorem ipsum dolor sit amet consectetur. Nibh lectus aliquam sagittis nisl faucibus. Sed adipiscing condimentum volutpat cursus in risus sed sit. Ipsum aliquam urna porttitor eu. Volutpat ac sit at semper tortor vulputate. Purus pulvinar vestibulum cras odio. Congue amet sagittis dui pellentesque consectetur pellentesque et fermentum. Arcu elementum tempor nulla quis aenean fusce ut vulputate. A quam vitae magna pellentesque. Ut volutpat adipiscing purus faucibus duis orci. Accumsan venenatis eu vitae interdum dolor. Nunc at nibh habitant condimentum vitae. Semper luctus vulputate lacinia sit diam tellus id vitae. Morbi aliquet bibendum scelerisque vestibulum aliquet venenatis eu et. Proin bibendum eget lectus consequat id vitae. Eu hendrerit lobortis turpis quam ornare egestas tincidunt donec nulla. Justo nisi ac diam mauris cursus turpis lacus. Vulputate cras sem nec id eget. Cras lectus vestibulum dictum enim. Mauris ultrices etiam ac facilisis malesuada. Odio accumsan fringilla malesuada faucibus fusce pellentesque. Non nunc cursus nisl odio. Pellentesque laoreet molestie proin tincidunt cursus. Integer non odio turpis ac sem aliquam in ante congue. Erat pharetra sed semper duis duis penatibus. Ut congue interdum cras convallis eu nibh quis. Arcu at accumsan neque ultricies tellus massa leo nulla sed.",
};

export const walletData = [
  {
    transcationId: "#12324654685",
    date: "26/01/2024",
    subscription: "Expertise Basic",
    name: "Rohit",
    amount: "₹1,999 ",
    invoice: invoiceImg,
  },
  {
    transcationId: "#12324654685",
    date: "26/01/2024",
    subscription: "Expertise Basic",
    name: "Varun",
    amount: "₹1,999 ",
    invoice: invoiceImg,
  },
  {
    transcationId: "#12324654685",
    date: "26/01/2024",
    subscription: "Expertise Basic",
    name: "Amit",
    amount: "₹1,999 ",
    invoice: invoiceImg,
  },
  {
    transcationId: "#12324654685",
    date: "26/01/2024",
    subscription: "Expertise Basic",
    name: "Shivam",
    amount: "₹1,999 ",
    invoice: invoiceImg,
  },
  {
    transcationId: "#12324654685",
    date: "26/01/2024",
    subscription: "Expertise Basic",
    name: "Vinit",
    amount: "₹1,999 ",
    invoice: invoiceImg,
  },
  {
    transcationId: "#12324654685",
    date: "26/01/2024",
    subscription: "Expertise Basic",
    name: "Priyank",
    amount: "₹1,999 ",
    invoice: invoiceImg,
  },
  {
    transcationId: "#12324654685",
    date: "26/01/2024",
    subscription: "Expertise Basic",
    name: "Nikhil",
    amount: "₹1,999 ",
    invoice: invoiceImg,
  },
  {
    transcationId: "#12324654685",
    date: "26/01/2024",
    subscription: "Expertise Basic",
    name: "Rohit",
    amount: "₹1,999 ",
    invoice: invoiceImg,
  },
  {
    transcationId: "#12324654685",
    date: "26/01/2024",
    subscription: "Expertise Basic",
    name: "Mohan",
    amount: "₹1,999 ",
    invoice: invoiceImg,
  },
];
