import { logo, 
  userImg, userBck, 
  stars, telegram, 
  arrow, expertise,
  stock_1, stock_2, stock_3,
  secondExpertise, courseImg,
  courseImg2, courseImg3, courseUser,
 } 
from "../assets";

export const navLinks = [
  {
    id: "home",
    title: "Home",
  },
  {
    id: "subscription",
    title: "Subscription",
  },
  {
    id: "expertise",
    title: "Expertise",
  },
  {
    id: "webinar",
    title: "Webinar",
  },
  {
    id: "wallet",
    title: "Wallet",
  },
];

export const expertise_type = [
  {
    id: 1,
    image: expertise,
    title: 'Futures',
    followers: '4K + More',
    describe: 'Our SEBI Registered experts with their expertise, help traders gain a deeper understanding of risk management, leverage, and market dynamics for profitability.',
    button: 'Explore All',
    arrowIcon: arrow,
  }, 
  {
    id: 2,
    image: expertise,
    title: 'Commodity',
    followers: '4K + More',
    describe: 'Our SEBI Registered experts with their expertise, help traders gain a deeper understanding of risk management, leverage, and market dynamics for profitability.',
    button: 'Explore All',
    arrowIcon: arrow,
  }, 
  {
    id: 3,
    image: expertise,
    image2: secondExpertise,
    title: 'Equity',
    followers: '4K + More',
    describe: 'Our SEBI Registered experts with their expertise, help traders gain a deeper understanding of risk management, leverage, and market dynamics for profitability.',
    button: 'Explore All',
    arrowIcon: arrow,
  }, 
]

export const expertise_data = [
  {
    id: "1",
    icon: userBck,
    userImg: userImg,
    name:"Arun Kumar",
    title: 'Stock Market',
    ratingIcon: stars,
    rating: '4.4',
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: 'Join Telegram',
    arrowIcon: arrow,
  },
  {
    id: "2",
    icon: userBck,
    userImg: userImg,
    name:"Arun Kumar",
    title: 'Stock Market',
    ratingIcon: stars,
    rating: '4.4',
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: 'Join Telegram',
    arrowIcon: arrow,
  },
  {
    id: "3",
    icon: userBck,
    userImg: userImg,
    name:"Arun Kumar",
    title: 'Stock Market',
    ratingIcon: stars,
    rating: '4.4',
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: 'Join Telegram',
    arrowIcon: arrow,
  },
  {
    id: "4",
    icon: userBck,
    userImg: userImg,
    name:"Arun Kumar",
    title: 'Stock Market',
    ratingIcon: stars,
    rating: '4.4',
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: 'Join Telegram',
    arrowIcon: arrow,
  },
  {
    id: "5",
    icon: userBck,
    userImg: userImg,
    name:"Arun Kumar",
    title: 'Stock Market',
    ratingIcon: stars,
    rating: '4.4',
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: 'Join Telegram',
    arrowIcon: arrow,
  },
  {
    id: "6",
    icon: userBck,
    userImg: userImg,
    name:"Arun Kumar",
    title: 'Stock Market',
    ratingIcon: stars,
    rating: '4.4',
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    content:
      "Have full control of your business finances on the go using our iOS/Android mobile apps. Because, you know, it’s 2023.",
    telegram: telegram,
    greet: 'Join Telegram',
    arrowIcon: arrow,
  },
];

export const stock_data = [
  {
    id: "1",
    content:
      "Ask anything, anytime, anywhere. Stuck while programming? Need some copy? Or just have a question - Ask AI.",
    title: "Lorem Ipsum Dolor",
    img: stock_1,
  },
  {
    id: "2",
    content:
      "Keep everything safe and updated across your Macs. Perfect to switch between personal and work setup.",
    title: "Lorem Ipsum Dolor",
    img: stock_2,
  },
  {
    id: "3",
    content:
      "Make Raycast your own with gorgeous pre-made themes or design your own and share it with the community.",
    name: "Kenn Gallagher",
    title: "Lorem Ipsum Dolor",
    img: stock_3,
  },
];

export const courseExpertise_data = [
  {
    id: "1",
    cardImg: courseImg,
    title: "Insights at your fingertips 1",
    image: courseUser,
    userName: 'Rohit Aggi',
    ratingIcon: stars,
    rating: '4.4',
    telegramImg: telegram,
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    callTime: 'Duration : 3 hrs',
    callSession: 'Session : 3',
    price: '₹1,999',
    btn: 'Buy Now',
  },
  {
    id: "2",
    cardImg: courseImg,
    title: "Insights at your fingertips 2",
    image: courseUser,
    userName: 'Rohit Aggi',
    ratingIcon: stars,
    rating: '4.4',
    telegramImg: telegram,
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    callTime: 'Duration : 3 hrs',
    callSession: 'Session : 3',
    price: '₹1,999',
    btn: 'Buy Now',
  },
  {
    id: "3",
    cardImg: courseImg,
    title: "Insights at your fingertips 3",
    image: courseUser,
    userName: 'Rohit Aggi',
    ratingIcon: stars,
    rating: '4.4',
    telegramImg: telegram,
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    callTime: 'Duration : 3 hrs',
    callSession: 'Session : 3',
    price: '₹1,999',
    btn: 'Buy Now',
  },
  {
    id: "4",
    cardImg: courseImg2,
    title: "Insights at your fingertips 4",
    image: courseUser,
    userName: 'Rohit Aggi',
    ratingIcon: stars,
    rating: '4.4',
    telegramImg: telegram,
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    callTime: 'Duration : 3 hrs',
    callSession: 'Session : 3',
    price: '₹1,999',
    btn: 'Buy Now',
  },
  {
    id: "5",
    cardImg: courseImg3,
    title: "Insights at your fingertips 5",
    image: courseUser,
    userName: 'Rohit Aggi',
    ratingIcon: stars,
    rating: '4.4',
    telegramImg: telegram,
    experience: 'Experience',
    totalExp: '7+',
    followers: 'Followers',
    totalFollowers: '3.1k',
    callTime: 'Duration : 3 hrs',
    callSession: 'Session : 3',
    price: '₹1,999',
    btn: 'Buy Now',
  },
];
