import React from "react";
import styles from "../../style";

const Terms = () => {
  return (
    <div
      className={`flex md:flex-col ${styles.paddingY} ${styles.paddingX} flex-col expertise-Bg`}
    >
      <div className="flex flex-col items-center">
        <div className="flex md:flex-row items-center flex-col justify-center gap-[1rem]">
          <div className={`flex-col text-center md:gap-[2rem] gap-0`}>
            <div className="flex flex-col justify-between">
              <span className="flex items-left font-inter font-[700] md:text-[72px] text-[40px] text-gradient md:leading-[84px] leading-[48px]">
                TERMS AND CONDITIONS
              </span>

              <div className="md:w-full md:h-[206px] h-[522px] text-left md:px-0 px-[1rem] md-px-0">
                <span className="font-inter font-[500] mt-4 text-dimWhite md:text-[18px] text-[16px] md:leading-[28px] leading-[16px]">
                  These terms of use (“Terms”) mandate the terms on which the
                  content creators (“You” or “Your” or “Yourself” or “User”)
                  access and register on the website ‘www.copartner.in’ owned
                  and operated by Hailgro Tech Solutions Pvt Ltd. (“Company”),
                  having its registered office at 546, 5th floor, JMD MEGAPOLIS,
                  Sector 48, Gurugram, Haryana 122018, collectively referred to
                  as (“the Platform”), for the purpose of availing the Services
                  (as defined hereinafter) provided by the Company.
                </span>

                <br />

                <span className="font-inter font-[500] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px] leading-[16px] mt-[4rem]">
                  These Terms are an electronic record in terms of the Indian
                  Contract Act, 1872; The Information Technology Act, 2000 and
                  rules made thereunder as applicable. The Terms is <br />{" "}
                  <span className="text-white">(i)</span> published in
                  accordance with the provisions of Rule <br />{" "}
                  <span className="text-white">3(1)(a)</span> of the Information
                  Technology (Intermediary Guidelines and Digital Media Ethics
                  Code) Rules, 2021, and amendments from time to time; and{" "}
                  <br /> <span className="text-white">(ii)</span> generated by a
                  computer system and does not require any physical, electronic,
                  or digital signatures.
                </span>
              </div>

              <div className="font-inter md:w-full md:h-[306px] h-[500px] py-[4rem] text-left md:px-0 px-[1rem]">
                <span className="font-[500] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px] md:leading-[16px] leading-[12px]">
                  Please read the Terms and Privacy Policy ( “Privacy Policy” )
                  carefully before using or registering on the Platform or
                  accessing any material, information through the Platform. By
                  accessing the Platform as a User, You accept these Terms and
                  Privacy Policy and agree to be legally bound by the same.
                  Further, by furnishing Your Personal Information (as defined
                  in the Privacy Policy) (“Personal Information”) to the Company
                  or giving Your consent to the Company to access Your Personal
                  Information for the purpose of rendering the Services (as
                  defined below), You also agree that You are interested in
                  availing the Services through the Platform in accordance with
                  these Terms.
                  <hr />
                  <span className="font-[700] text-white text-[16px] text-center">
                    IF YOU DO NOT AGREE TO BE BOUND BY ALL TERMS AND CONDITIONS
                    CAPTURED IN THE TERMS, PLEASE DO NOT USE THE PLATFORM OR
                    SERVICES
                  </span>
                  <hr />
                </span>
              </div>
            </div>

            <div
              className={`flex flex-col md:w-[1190px] md:pt-0 pt-[5rem]`}
            >
              <div className="flex flex-col">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                  text-gradient-2 leading-[51px] md:w-[635px] md:h-[60px] w-[365px] h-[40px] text-start"
                >
                  1. Applicability:
                </span>
                <div className="flex flex-col text-start">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2 md:px-0 px-[1rem]"
                  >
                    These Terms shall be applicable to You only if You have
                    created an account on the Platform (“Account”) by providing
                    such information as may be required as set out further in
                    Our Privacy Policy.
                  </span>
                </div>
              </div>
            </div>

            <div className={`flex flex-col md:w-[1190px] pt-[2rem]`}>
              <div className="flex flex-col">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 leading-[51px] md:w-[635px] md:h-[60px] w-[365px] h-[40px] text-start"
                >
                  2. Eligibility to Use:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    2.1. You shall be eligible to avail Services on the Platform
                    subject to registering with Us as a User and holding an
                    Account as detailed in Clause 3 below and subject to
                    executing a service agreement with the Company (“Service
                    Agreement”).
                  </span>
                </div>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    2.2. The Services are not available to minors i.e., persons
                    under the age of 18 (eighteen) years or to any Users
                    suspended or removed by the Company for any reason
                    whatsoever. By using Platform, You affirm that <br />{" "}
                    <span className="text-white">(a)</span> You are at least 18
                    years of age; or <br />{" "}
                    <span className="text-white">(b)</span> are a corporation,
                    duly organised, validly existing and in good standing under
                    the laws of the jurisdiction of Your organisation, and are
                    fully able and competent to enter into the Terms,
                    conditions, obligations, affirmations, representations,
                    warranties set forth in the Terms and Conditions, and to
                    abide by and comply with the Terms stated therein.
                    Registration of User and creation of Account on the Platform
                    is available only to persons who can form legally binding
                    contracts under Indian Contract Act, 1872.
                  </span>
                </div>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    2.3. We maintain the right to provide Services to only those
                    Users who are – <br />{" "}
                    <span className="text-white">(a)</span> competent to enter
                    into legally binding contracts, <br />{" "}
                    <span className="text-white">(b)</span> have made the
                    representations as provided above, <br />{" "}
                    <span className="text-white">(c)</span> and also qualify
                    under the internal policy(ies) for the same determined
                    solely by Us from time to time. We shall have the sole right
                    to change, modify, add, or remove, in whole or in part,
                    internal policy(ies), in relation to the provision of the
                    Services at any time by providing a prior written notice or
                    intimation to the Users.
                  </span>
                </div>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    2.4. You shall not have more than one active Account on the
                    Platform. Additionally, You are prohibited from selling,
                    trading, or otherwise transferring Your Account to another
                    party or impersonating any other person for the purpose of
                    creating an Account with the Platform.
                  </span>
                </div>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    2.5. You hereby agree and acknowledge that the Company
                    allows You to register on the Platform based on a
                    preliminary examination of the information provided by You
                    on the Platform during the creation of Your Account. The
                    Company does not and will not undertake any fact finding or
                    verification process to evaluate the veracity of the
                    information provided by You or on the basis of how the
                    Platform is subsequently used by You including but not
                    limited to content shared by You through the usage of the
                    Platform.
                  </span>
                </div>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    2.6. By accessing the Platform or by accessing the Software
                    or any of the Services, it is deemed that the User has read
                    and understood and accepted these Terms and has executed the
                    Service Agreement and agreed to be bound by it. If You will
                    be using the Services on behalf of an organisation, You
                    agree to these Terms on behalf of that organisation and You
                    represent that You have the authority to do so.
                  </span>
                </div>
              </div>

              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 leading-[51px] md:w-[735px] md:h-[60px] w-[365px] h-[40px] text-start"
                >
                  3. User Account Registration:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    3.1. You may browse certain sections of the Platform without
                    having an Account with Us. However, to avail the Services
                    (defined below) on the Platform ,You need to create an
                    Account by providing such information as may be required by
                    the Company as provided under the Privacy Policy. Such
                    details may also include proof of identification in a manner
                    prescribed by the Company from time to time. You may create
                    Your Account on the Platform by entering the one time
                    verification password generated by the Company for this
                    purpose which shall be sent to the phone number entered by
                    You on the Platform.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    3.2. You shall ensure and confirm that the Account
                    information and all information provided by You is complete,
                    accurate and up-to-date. If there is any change in the
                    Account information, or if any information is found to be
                    incomplete or incorrect, You shall promptly update Your
                    Account information on the Platform or request the Company
                    for an information revision or update. If You provide any
                    information that is untrue, inaccurate, unauthorised, not
                    current, or incomplete (or becomes untrue, inaccurate, not
                    current, or incomplete), or if the Company has reasonable
                    grounds to suspect that such information is untrue,
                    inaccurate, not current, or incomplete, the Company has the
                    right to refuse any and all the Services to You.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    3.3. You are responsible for maintaining the confidentiality
                    of the Account information, safeguarding the password or
                    credentials that You use to access the Service and for any
                    activities or actions under Your Account. You are encouraged
                    to use “strong” passwords (passwords that use a combination
                    of upper and lower-case letters, numbers and symbols) with
                    Your Account and with other accounts that You may connect to
                    Your Account (such as Your Accounts with other social media
                    platforms).
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    3.4. You agree to (a) immediately notify the Company of any
                    unauthorised use of Your Account information or any other
                    breach of security, and (b) ensure that You exit from Your
                    Account at the end of each session. The Company will not be
                    liable for any loss that You may incur as a consequence of
                    unauthorised use of Your Account either with or without Your
                    knowledge.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    3.5. You may be held liable for losses incurred by the
                    Company or any other User of or visitor of the Platform due
                    to authorised or unauthorised use of Your Account as a
                    result of Your failure in keeping Your Account information
                    secure and confidential.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    3.6. You hereby acknowledge and agree that the deletion of
                    the Platform from Your device does not constitute
                    termination of Your Account and agree to undertake the
                    process detailed herein in order to complete the
                    de-registration of Your Account (“De-registration”). If and
                    when You are desirous of having Your name and other details
                    removed from Our records, immediately upon receiving Your
                    written request to that effect, We shall remove and/delete
                    all such information. However, We may retain certain
                    information regarding Your Account, even after receiving a
                    deletion request from You, where such retention is required
                    under applicable laws or such information is non-personally
                    identifiable and aggregated information. You hereby
                    acknowledge that the removal of Your details from the
                    Platform does not constitute termination of Your outstanding
                    obligations, if any, to the Company.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    3.7. The information collected while creating Your Account
                    or processed for the purposes of availing the Services, will
                    be governed by Our Privacy Policy.
                  </span>
                </div>
              </div>
              <div className="flex flex-col md:pt-[3rem] pt-[2rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 leading-[51px] md:w-[735px] md:h-[60px] w-[365px] h-[40px] text-start"
                >
                  4. Services:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    4.1. A limited, non–exclusive, non–transferable, royalty
                    free licence to use the Platform for the purposes of
                    registering on the Platform by creating an Account, and
                    accessing the Software;
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    4.2. Access to digital products/tools in the form of a
                    software as a service (“Software”) that gives You the
                    opportunity to create or share content and generate or
                    access links/ subdomains to third party social media
                    platforms through which You can make available such content
                    to any third party users on such third party platforms
                    (“Third Party Platforms”)
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    4.3. Opportunity to enable You to monetize Your services to
                    third party users by assisting with facilitation of
                    payments, either directly acting as Your collection agent or
                    in association with other third party payment aggregators or
                    payment intermediaries. The aforementioned services shall be
                    collectively referred to as the “Services”. The Company may,
                    at its discretion, add, modify, or remove any of the
                    Services listed above from time to time without special
                    notice to You
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    4.4. All Services on the Platform are provided to You on a
                    principal to principal basis between You and the Company.
                    Nothing herein is intended to nor be construed to constitute
                    the relationship of a principal and agent, employer and
                    employee, partners, joint venture, co-owners or otherwise as
                    participants in a joint undertaking or representative of the
                    other for any purpose whatsoever.
                  </span>
                </div>
              </div>
              <div className="flex flex-col md:py-[3rem] py-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] leading-[30px] md:w-[935px] md:h-[70px] w-[365px] h-[60px] text-start"
                >
                  5. Updation of Terms and Conditions:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    5.1. Your use of the Platform is subject to the Terms, which
                    may be updated, amended, modified or revised by Us from time
                    to time without notice to You and subject to the terms of
                    the Service Agreement. To ensure that You are aware of any
                    additions, revisions, amendments or modifications that We
                    may have made to these Terms, it is important for You to
                    refer to the Terms from time to time. You can determine when
                    this Terms was last modified by referring to the “Last
                    Updated” legend.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    5.2. The updated Terms shall be effective immediately and
                    shall supersede these. It shall be Your responsibility to
                    check these Terms periodically for changes. Your continued
                    use of the Services post amendment of Terms shall signify
                    Your consent to such amendment, and agreement to be legally
                    bound by the same.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    5.3. Any reference to the Terms shall refer to the latest
                    version of these Terms.
                  </span>
                </div>
              </div>
              <div className="flex flex-col md:pt-[1rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[285px] h-[35px] text-start"
                >
                  6. Rules and Conduct:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    6.1. As a condition of use, You promise not to use the
                    Services for any purpose that is prohibited by the Terms; or
                    other rules or policies implemented by Us from time to time;
                    or in violation of any applicable laws.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    6.2. By way of example, and not as a limitation, You shall
                    not (and shall not permit any third party to) take any
                    action on the Platform that:{" "}
                    <span className="text-white">
                      {" "}
                      <br /> (i)
                    </span>{" "}
                    would constitute a violation of any applicable law, rule or
                    regulation;{" "}
                    <span className="text-white">
                      {" "}
                      <br /> (ii){" "}
                    </span>
                    infringes on any intellectual property or other right of any
                    other person or entity; <br />{" "}
                    <span className="text-white">(iii)</span> is threatening,
                    abusive, harassing, defamatory, libellous, deceptive,
                    fraudulent, invasive of another’s privacy, tortuous,
                    obscene, offensive, or profane; or <br />{" "}
                    <span className="text-white">(iv)</span> impersonates any
                    person or entity. The Company reserves the right to disable
                    any Account from the Platform at any time for any reason
                    (including, but not limited to, upon receipt of claims or
                    allegations from third parties or authorities; or if Company
                    is concerned that You may have violated the Terms of
                    Service), or for no reason at all with or without notice to
                    the User/Users.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    6.3. Additionally, You shall not share any information on
                    the Platform or through the links to Third Party Platforms
                    created using the Software that:{" "}
                    <span className="text-white">
                      {" "}
                      <br /> (i)
                    </span>{" "}
                    may be harmful to minors or children below the age of 18
                    (eighteen) years;
                    <span className="text-white">
                      {" "}
                      <br /> (ii)
                    </span>{" "}
                    threatens the unity, integrity, defence, security or
                    sovereignty of India, friendly relations with foreign states
                    or public order or causes incitement to the commission of
                    any cognizable offence or prevents investigation of any
                    offence or is insulting any other nation; and <br />{" "}
                    <span className="text-white">(iii)</span> is invasive of
                    another’s privacy, hateful, or racially, ethnically
                    objectionable, disparaging, relating or encouraging money
                    laundering or gambling, or otherwise unlawful in any manner
                    whatever; <br /> <span className="text-white">(iv)</span>{" "}
                    harms minors in any manner; <br />{" "}
                    <span className="text-white">(v)</span> infringes any
                    patent, trademark, copyright or other proprietary rights;{" "}
                    <br /> <span className="text-white">(vi)</span> violates any
                    laws for time being; and <br />{" "}
                    <span className="text-white">(vii)</span> impersonate any
                    person.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    6.4. Furthermore, You shall not (directly or indirectly) on
                    the Platform or through the links to Third Party Platforms
                    created using the Software: <br />{" "}
                    <span className="text-white">(i)</span> take any action that
                    imposes or may impose an unreasonable or disproportionately
                    large load on Company’s (or its third party providers’)
                    infrastructure; <br />{" "}
                    <span className="text-white">(ii)</span> interfere or
                    attempt to interfere with the proper working of the Platform
                    or any activities conducted on the Platform; <br />{" "}
                    <span className="text-white">(iii)</span> bypass any
                    measures We may use to prevent or restrict access to the
                    Platform (or parts thereof); <br />{" "}
                    <span className="text-white">(iv)</span> decipher,
                    decompile, disassemble, reverse engineer or otherwise
                    attempt to derive any source code or underlying ideas or
                    algorithms of any part of the Platform, except to the
                    limited extent applicable laws specifically prohibit such
                    restriction; <br /> <span className="text-white">(v)</span>{" "}
                    modify, translate, or otherwise create derivative works of
                    any part of the Platform; or <br />{" "}
                    <span className="text-white">(vi)</span> copy, rent, lease,
                    distribute, or otherwise transfer any or all of the rights
                    that You receive hereunder.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    6.5. You will not access the Platform, and/or its Services,
                    or the personal information of other Users, available on the
                    Platform in order to build a similar or competitive
                    application, product, or service.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    6.6. You agree to immediately notify Us of any unauthorised
                    use, or suspected unauthorised use of Your Profile, or any
                    other breach of security, in relation to Your personal
                    information on the Platform.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    6.7. One Account shall not be used by more than one User.
                    Any use of an Account by a third-party would deem to be
                    unauthorised usage. The Company reserves the right to
                    disable any such Account from the Platform.
                  </span>
                </div>
              </div>
              <div className="flex flex-col md:pt-[4rem] pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] leading-[30px] md:w-[935px] md:h-[70px] w-[325px] h-[60px] text-start"
                >
                  7. Profile Ownership and Editing Rights:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    7.1. We ensure easy access to the Users by providing a tool
                    to update Your profile information. We reserve the right to
                    moderate the changes or updates requested by You and We
                    shall take an independent decision whether to publish or
                    reject the requests submitted for the respective changes or
                    updates in Your profile.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    7.2. You hereby represent and warrant that You are fully
                    entitled, under applicable law, to provide information as
                    part of Your profile or otherwise while using Our Services,
                    and that no such information breaches any third-party
                    rights, including intellectual property rights and
                    applicable data protection laws. Upon becoming aware of a
                    breach of the foregoing representation, We may modify or
                    delete parts of Your profile information at Our sole
                    discretion with or without notice to You. Excluding Your
                    Account information, You acknowledge that the Platform, the
                    entire Company Content , Services, and all the intellectual
                    property rights, including copyrights, patents, trademarks,
                    designs, and trade secrets in relation to the above are
                    solely owned by Us.
                  </span>
                </div>
              </div>
              <div className="flex flex-col md:pt-[3rem] pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] leading-[30px] md:w-[935px] md:h-[110px] w-[385px] h-[90px] text-start"
                >
                  8. Rights and Obligation relating to the usage of the
                  Platform:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    8.1. Users shall be prohibited from carrying out the any
                    illegal acts in the Platform or through the links to Third
                    Party Platforms created using the Software including but not
                    limited to acts mentioned below: <br />{" "}
                    <span className="text-white">a )</span> violating or
                    attempting to violate the integrity or security of the
                    Platform; <br /> <span className="text-white">b )</span>{" "}
                    transmitting any information on or through the Platform that
                    is disruptive or competitive to the provision of Our
                    Services; <br /> <span className="text-white">c )</span>{" "}
                    intentionally submitting on the Platform any incomplete,
                    false or inaccurate information; <br />{" "}
                    <span className="text-white">d )</span> using any engine,
                    software, tool, agent or other device or mechanism (such as
                    spiders, robots, avatars or intelligent agents) to navigate
                    or search the Platform or any Third Party Platform;
                    <br /> <span className="text-white">e )</span> circumventing
                    or disabling any digital rights management, usage rules, or
                    other security features of the Platform. Any unlawful
                    activities in the Platform which are prohibited by laws of
                    India
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    8.2. The Company shall, upon obtaining knowledge by itself
                    or been brought to actual knowledge by an affected person in
                    writing or through email signed with electronic signature
                    Your violation of these Terms, be entitled to disable Your
                    Access to the Account and use of Services. We shall also be
                    entitled to preserve such information and associated records
                    for at least 90 (ninety) days or such shorter time as
                    prescribed by law, for production to governmental
                    authorities for investigation purposes. In case of
                    non-compliance with these Terms, any applicable laws, rules
                    or regulations, the Service Agreement or the Privacy Policy
                    by a User, We shall have the right to immediately terminate
                    Your access or usage rights to the Platform and Services and
                    to remove non-compliant information from the Platform.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    8.3. We may disclose or transfer User-generated information
                    to Our affiliates or governmental authorities in such manner
                    as permitted or required by applicable law, and You hereby
                    consent to such transfer. In accordance with the applicable
                    laws, We shall transfer sensitive personal data or
                    information including any information, to any other body
                    corporate or a person in India, or located in any other
                    country, that ensures the same level of data protection that
                    is adhered to by Us, only if such transfer is necessary for
                    the performance of the lawful contract between Company or
                    any person on its behalf and the User or where the User has
                    consented to data transfer.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[305px] h-[35px] text-start"
                >
                  9. Third Party Services:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    9.1. While availing Services, Users may connect with
                    third-party service providers. The Company is not
                    responsible for, and does not endorse, any third-party
                    services mentioned on the Platform. It is hereby stated that
                    the Company shall in no way be responsible for any acts or
                    omissions of third parties. Any transaction, dealings or
                    communication otherwise that the User may have with such
                    third parties are at the User’s own risk and We make no
                    warranties, express or implied regarding the quality or
                    suitability of the services or products of such third-party
                    vendors.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[285px] h-[35px] text-start"
                >
                  10. Confidentiality:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    10.1. The Parties may disclose to each other and their
                    designated agents and/or advisors Confidential Information
                    as may be required for the performance of the Services and
                    execution of a Campaign. 10.2. Each party undertakes that it
                    will keep secret and confidential the terms of the Service
                    Agreement and any Confidential Information supplied by
                    either party in connection with the Service Agreement or in
                    connection with the business of the other and in connection
                    with the Services and Campaign and shall only disclose such
                    information or part thereof (except to its own employees and
                    advisers and then only on a need to know basis) with the
                    other party’s prior written consent PROVIDED THAT this
                    clause shall not extend to information which was and can be
                    shown to be rightfully in the possession of the receiving
                    party prior to the commencement of the negotiations leading
                    to the Service Agreement or which is in the public domain
                    (other than as a result of a breach of this clause).
                  </span>
                </div>
              </div>
              <div className="flex flex-col md:pt-[4rem] pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] leading-[30px] md:w-[935px] md:h-[110px] w-[345px] h-[120px] text-start"
                >
                  11. Use of Your information and content displayed on the
                  Platform or Third Party Platforms:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    11.1 We will only use the information You provide as
                    permitted by Our Privacy Policy and applicable law. Please
                    closely review Our Privacy Policy for more information
                    regarding how We use and disclose Your personal information.
                    Our Privacy Policy is hereby incorporated into these Terms
                    of Service by this reference.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    <span
                      className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                    >
                      11.2 We will only use the information You provide as
                      permitted by Our Privacy Policy and applicable law. Please
                      closely review Our Privacy Policy for more information
                      regarding how We use and disclose Your personal
                      information. Our Privacy Policy is hereby incorporated
                      into these Terms of Service by this reference.
                    </span>
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    <span
                      className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                    >
                      11.3. You acknowledge and agree that We may preserve Your
                      information and may also disclose Your related information
                      if required to do so by law; or in the good faith belief
                      that such preservation or disclosure is reasonably
                      necessary to: <br />{" "}
                      <span className="text-white">(a)</span> comply with legal
                      process, applicable laws or government requests; <br />{" "}
                      <span className="text-white">(b)</span> enforce these
                      Terms; <br /> <span className="text-white">(c)</span>
                      respond to claims that any of Your usage of the Platform
                      violates the rights of third parties; <br />{" "}
                      <span className="text-white">(d)</span> detect, prevent,
                      or otherwise address fraud, security or technical issues;
                      or <br /> <span className="text-white">(e)</span> protect
                      the rights, property, or personal safety of the Platform,
                      its users, or the public. 11.4. We reserve the right to
                      remove or disable access to any user information hosted on
                      Our Platform.
                    </span>
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[375px] h-[75px] text-start"
                >
                  12. Intellectual Property Rights:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    12.1. The Platform and the processes, and their selection
                    and arrangement, including but not limited to, all text,
                    videos, graphics, user interfaces, visual interfaces, sounds
                    and music (if any), artwork and computer code (and any
                    combinations thereof) (collectively, the “Company Content”)
                    on the Platform is owned by the Company and the design,
                    structure, selection, coordination, expression, look and
                    feel and arrangement of such Company Content is protected by
                    copyright, patent and trademark laws, and various other
                    intellectual property rights.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    12.2. The trademarks, logos and service marks displayed on
                    the Platform (“Marks”) are the property of the Company or
                    other respective third parties, as the case may be. You are
                    not permitted to reproduce or distribute or otherwise use
                    the Marks without the prior consent of the Company or the
                    third party that may own the Marks.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[375px] h-[35px] text-start"
                >
                  13. Limitation of Liability:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    13.1. to the fullest extent permitted by law, in no event
                    shall company (including its directors, employees, agents,
                    sponsors, partners, suppliers, content providers, licensors
                    or resellers,) be liable under contract, tort, strict
                    liability, negligence or any other legal or equitable theory
                    with respect to the services <br />{" "}
                    <span className="text-white">(i)</span> for any lost
                    profits, data loss, loss of goodwill or opportunity, or
                    special, indirect, incidental, punitive, or consequential
                    damages of any kind whatsoever, <br />{" "}
                    <span className="text-white">(ii)</span> for your reliance
                    on the services <br />{" "}
                    <span className="text-white">(iii)</span> for any damages{" "}
                    <br /> <span className="text-white">(iv)</span>) for any
                    matter beyond its or their reasonable control, even if
                    company has been advised of the possibility of any of the
                    aforementioned damages <br />{" "}
                    <span className="text-white">(v)</span> for any third party
                    claims in relation to your use of the software or
                    content/information shared by you through/with the help of
                    the software.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[285px] h-[35px] text-start"
                >
                  14. Disclaimer:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    14.1. the service and platform is provided “as is” and “as
                    available” and is without warranty of any kind, express or
                    implied, including, but not limited to, the implied
                    warranties of title, non-infringement, merchantability and
                    fitness for a particular purpose, and any warranties implied
                    by any course of performance or usage of trade, all of which
                    are expressly disclaimed. the company and its directors,
                    employees, agents, suppliers, shareholders and partners do
                    not warrant that: <br />{" "}
                    <span className="text-white">(a)</span> the service will be
                    secure or available at any particular time or location;{" "}
                    <br /> <span className="text-white">(b)</span> the quality
                    of any services, availed by you through the service will
                    meet your expectations; <br />{" "}
                    <span className="text-white">(c)</span> any defects or
                    errors will be corrected; <br />{" "}
                    <span className="text-white">(d)</span> any content or
                    software available at or through the service is free of
                    viruses or other harmful components; or <br />{" "}
                    <span className="text-white">(e)</span> the results of using
                    the service will meet your requirements or the use of the
                    service will be accurate or reliable. your use of the
                    service is solely at your own risk.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[285px] h-[35px] text-start"
                >
                  15. Indemnification:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    15.1. You shall defend, indemnify, and hold harmless the
                    Company, its affiliates/subsidiaries/joint venture partners
                    and each of its, and its affiliates’/subsidiaries/joint
                    venture partners’ employees, contractors, directors,
                    suppliers and representatives from all liabilities, losses,
                    claims, and expenses, including reasonable attorneys’ fees,
                    that arise from or relate to <br />{" "}
                    <span className="text-white">(i)</span> Your use or misuse
                    of, or access to, the Services, Software and Platform; or{" "}
                    <br /> <span className="text-white">(ii)</span> Your
                    violation of the Terms and Conditions; or any applicable
                    law, contract, policy, regulation or other obligation
                    including that of the Third Party Platforms. We reserve the
                    right to assume the exclusive defence and control of any
                    matter otherwise subject to indemnification by You, in which
                    event You will assist and cooperate with Us in connection
                    therewith.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[285px] h-[35px] text-start"
                >
                  16. Fees/Payments:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    You agree and acknowledge that You shall be charged such
                    amount towards subscription of Services as set out in the
                    Service Agreement executed with the Company.
                  </span>
                </div>
              </div>
              <div className="flex flex-col md:pt-[4rem] pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[285px] h-[35px] text-start"
                >
                  17. Violation of the Terms:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    17.1. You agree that any violation by You of these Terms
                    will constitute an unlawful and unfair business practice,
                    and will cause irreparable harm to the Company, for which
                    monetary damages would be inadequate, and You consent to the
                    Company obtaining any injunctive or equitable relief that
                    they deem necessary or appropriate in such circumstances.
                    These remedies are in addition to any other remedies that
                    the Company may have at law or in equity.
                  </span>
                </div>
              </div>
              <div className="flex flex-col md:pt-[4rem] pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[285px] h-[70px] text-start"
                >
                  18. Suspension and Termination:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    18.1. The Terms will continue to apply until terminated by
                    either You or the Company as set forth below. If You object
                    to the Terms or are dissatisfied with the Platform, Your
                    only recourse is to <br />{" "}
                    <span className="text-white">(i)</span> close Your Account
                    on the Platform; and/or <br />{" "}
                    <span className="text-white">(ii)</span> stop accessing the
                    Platform.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    18.2. We may temporarily suspend access to the whole or any
                    part of the Services for pre-scheduled maintenance. The
                    intent to temporarily suspend access for pre-scheduled
                    maintenance shall be communicated to You 48 hours in advance
                    via email to the email id provided by You upon creation of
                    Your Account. If You choose to access the Platform or avail
                    Services during such pre-scheduled maintenance, We cannot
                    guarantee the availability of the Services and/or
                    functionality of the Platform.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    18.3. The Company may delist You or block Your future access
                    to the Platform or suspend or terminate Your Account if it
                    believes, in its sole and absolute discretion that You have
                    infringed, breached, violated, abused, or unethically
                    manipulated or exploited any term of these Terms or the
                    Privacy Policy or anyway otherwise acted unethically.
                    Notwithstanding anything in this clause, these Terms will
                    survive indefinitely unless and until the Company chooses to
                    terminate them.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    18.4. If You or the Company terminate Your use of the
                    Platform, the Company may delete any Company Content or
                    other materials relating to You and the Company shall have
                    no liability to You or any third party for doing so.
                    However, Your transaction details may be preserved by the
                    Company for purposes of tax or regulatory compliance.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    18.5. We may terminate Your usage of the Platform at any
                    time for any reason, including breach of the Terms. We have
                    the right (but not the obligation) to refuse to grant access
                    to Platform. Except for the rights and licence granted in
                    these terms, We reserve all other rights and grant no other
                    rights or licences, implied or otherwise.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    18.6. Once temporarily suspended, indefinitely suspended or
                    terminated, the User may not continue to use the Platform
                    under the same account, a different account or re-register
                    under a new account. On termination of an account due to the
                    reasons mentioned herein, such User shall no longer have
                    access to data, messages and other material kept on the
                    Platform by such User. All provisions of the Terms, which by
                    their nature should survive termination, shall survive
                    termination, including, without limitation, warranty
                    disclaimers, indemnity and limitations of liability.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    18.7. You shall be liable to pay any fees or charges as may
                    be applicable in respect of the Services until the date of
                    termination by either party whatsoever.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[335px] h-[70px] text-start"
                >
                  19. Exemptions to liability of Company:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    19.1. You further agree and confirm that Company shall not
                    be responsible, in any manner whatsoever, for any
                    delay/unavailability of Services or failure to meet its
                    obligations under the Terms and Conditions, which may be
                    caused, directly or indirectly, due to: <br />{" "}
                    <span className="text-white">a )</span> Your failure to
                    cooperate; <br /> <span className="text-white">b )</span>{" "}
                    Your unavailability and/or unresponsiveness;
                    <br /> <span className="text-white">c )</span> Your failure
                    to provide accurate and complete information; <br />{" "}
                    <span className="text-white">d )</span> any event beyond
                    Company’s reasonable control.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[305px] h-[70px] text-start"
                >
                  20. Governing Law and Jurisdiction:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    20.1. These Terms shall be governed by and construed in
                    accordance with the laws of India without regard to the
                    conflict of law provisions thereof. All claims, differences
                    and disputes arising under or in connection with or in
                    relation hereto the Platform or Services, the Terms or any
                    transactions entered into on or through the Platform or
                    Services shall be subject to the exclusive jurisdiction of
                    the courts at Bangalore, Karnataka, India and You hereby
                    accede to and accept the jurisdiction of such courts.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[305px] h-[35px] text-start"
                >
                  21. General Provisions:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    21.1. Notice: All notices under the Terms and Conditions
                    will be in writing and will be deemed to have been duly
                    given when received, if personally delivered or sent by
                    certified or registered mail, return receipt requested; when
                    receipt is electronically confirmed, if transmitted by
                    facsimile or e-mail; or two days after it is sent, if sent
                    for next day delivery by recognized overnight delivery
                    service.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    21.2. Assignment: You cannot assign or otherwise transfer
                    the Terms, or any rights granted hereunder to any third
                    party. The Company’s rights under the Terms are freely
                    transferable by the Company to any third party without the
                    requirement of seeking Your consent
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    21.3. Relationship: No agency, partnership, joint venture,
                    or employment relationship is created as a result of the
                    Terms and Conditions and neither party has any authority of
                    any kind to bind the other in any respect.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    21.4. Severability: If, for any reason, a court of competent
                    jurisdiction finds any provision of the Terms, or any
                    portion thereof, to be unenforceable, that provision shall
                    be enforced to the maximum extent permissible so as to give
                    effect to the intent of the parties as reflected by that
                    provision, and the remainder of the Terms shall continue in
                    full force and effect.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    21.5. Waiver: Any failure by Company to enforce or exercise
                    any provision of the Terms, or any related right, shall not
                    constitute a waiver by Company of that provision or right.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[305px] h-[70px] text-start"
                >
                  22. Alerts Provided by The Company:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    22.1. The Company provides You with multiple automatic
                    alerts while providing Services.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    22.2. You understand and agree that any alerts provided to
                    You through the Platform may be delayed or prevented by a
                    variety of factors. We will do Our best to provide alerts in
                    a timely manner with accurate information. However, We
                    neither guarantee the delivery nor the accuracy of the
                    content of any alert. You also agree that We shall not be
                    liable for any delays, failure to deliver, or misdirected
                    delivery of any alert; for any errors in the content of an
                    alert; or for any actions taken or not taken by You or any
                    third party in reliance on an alert.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[265px] h-[35px] text-start"
                >
                  23. Contact You:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    23.1. You agree that We may contact You through telephone,
                    email, SMS, or any other means of communication for the
                    purpose of: <br /> <span className="text-white">a )</span>{" "}
                    Obtaining feedback in relation to Platform or Our Services;{" "}
                    <br /> <span className="text-white">b )</span> Resolving any
                    complaints, information, or queries; and <br />{" "}
                    <span className="text-white">c )</span> You agree to provide
                    Your fullest cooperation further to such communication by
                    Company.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    23.2. By submitting suggestions or other feedback regarding
                    Our Services/Platform, You agree that We can use and share
                    such feedback for any purpose without any compensation to
                    You and We are under no obligation to keep such feedback
                    confidential.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[305px] h-[70px] text-start"
                >
                  24. Grievance Redressal Mechanism:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    24.1. Any discrepancies or grievances with regard to content
                    and or comment or breach of the Terms and Conditions shall
                    be taken up with the designated Grievance Officer as
                    mentioned below via in writing or through email signed with
                    the electronic signature to
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    Attention: Anshu Hooda <br /> Email: info@copartner.in{" "}
                    <br /> Address: 546, 5th floor, JMD MEGAPOLIS, Sector 48,
                    Gurugram, Haryana 122018 24.2. In furtherance of the
                    Consumer Protection Act 2019 and the Consumer Protection
                    (E-Commerce) rules 2020 nodal officer appointed to ensure
                    compliance (to the extent relevant and applicable on the
                    Company) with the Act and E-commerce Rules is as follows:{" "}
                    <br /> Name: Anshu Hoodal
                    <br /> Attention: Anshu Hooda, HR <br /> Contact Details:
                    info@copartner.in Designation of such officer: HR <br />{" "}
                    24.3. The grievance officer will acknowledge the receipt of
                    any complaint within 24 hours and redress the complaint
                    within 15 days from receipt of the complaint.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[305px] h-[70px] text-start"
                >
                  25. Company and User Materials:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    25.1. While rendering Services, Company directly or through
                    its representatives, may provide Users with certain
                    materials relevant to the Services, which may be in the form
                    of audio, video, written and oral content (“Company
                    Materials”). Company Materials shall be the exclusive
                    property of the Company. User hereby agrees and acknowledges
                    that he/she shall ensure that the Company Materials are not
                    shared with any third party, without Company’s written
                    consent and any breach of such nature shall cause financial
                    and irreparable injury to Company. Company hereby provides
                    User with a revocable, non-exclusive, non-transferable,
                    non-sublicensable, limited licence to use the Company
                    Materials solely for its personal purpose and not for any
                    commercial use. While availing Services, User may submit
                    various materials to Company in the form of
                    audio/video/image/written content, (“User Materials”). User
                    hereby provides Company with an exclusive, transferrable,
                    perpetual and irrevocable licence to use the User Materials
                    for its use. User hereby agrees and acknowledges that User
                    Materials shall not infringe any intellectual property
                    rights of third parties and shall be responsible for any
                    claims arising out of infringement.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[305px] h-[35px] text-start"
                >
                  26. Modification:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[16px] text-start mt-2"
                  >
                    26.1. We reserve the right, at any time and with sole
                    discretion, to change, modify, or amend the Platform (in
                    whole, or in part) or any of its Services or Company Content
                    (in whole, or in part), in compliance with the applicable
                    legal and regulatory framework. You agree that We will not
                    be liable to You for any change, modification or amendment
                    of the Platform or its Services, or any part thereof
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[305px] h-[35px] text-start"
                >
                  27. Support:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[16px] text-start mt-2"
                  >
                    27.1. The Company offers a chat-based support system along
                    with an online knowledge pool of FAQs. In case You require
                    any assistance or support, You may access support resources
                    or contact Our support by emailing at
                    support@info@copartner.in and raise a ticket for Your query
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[16px] text-start mt-2"
                  >
                    27.2. The Company shall revert to every complaint within 24
                    hours of receipt of the complaint. Further, the Company
                    shall take best possible efforts to redress the complaint
                    within 15 days of receipt of the complaint. Any suggestions
                    by Company regarding use of the Services shall not be
                    construed as a warranty.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[16px] text-start mt-2"
                  >
                    27.3. The User agrees and acknowledges that the Company
                    shall address and attempt to resolve the complaint received
                    in accordance with the standard policies and procedures
                    adopted by the Company, the User’s disapproval/discontent
                    with the outcome/mode of redressal shall not be deemed to
                    mean non-redressal of the complaint by the Company. Any
                    suggestions by Company regarding use of the Service shall
                    not be construed as a warranty.
                  </span>
                </div>
              </div>
              <div className="flex flex-col pt-[3rem]">
                <span
                  className="font-inter font-[700] md:text-[50px] text-[25px] md:px-0 px-[1rem]
                    text-gradient-2 md:leading-[51px] md:w-[935px] md:h-[70px] w-[305px] h-[35px] text-start"
                >
                  28. Contact:
                </span>
                <div className="flex flex-col text-start md:px-0 px-[1rem]">
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[16px] text-start mt-2"
                  >
                    28.1. If You have any questions regarding the Services or
                    usage of the Platform, please contact the Company at
                    support@info@copartner.in. Please note that for the purpose
                    of validation, You shall be required to provide information
                    (including, but not limited to contact number or registered
                    mobile number, etc.) for the purpose of validation and
                    taking Your service request.
                  </span>
                  <span
                    className="font-inter font-[400] text-dimWhite md:text-[18px] text-[16px] md:leading-[28px]
                   leading-[21px] text-start mt-2"
                  >
                    Copyright © All rights reserved. <br /> Last Updated : 10 April 24
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Terms;
